### PR TITLE
feat: support array of path with name (sync `all` method)

### PR DESCRIPTION
**Pull request by JounQin**

### CODE REVIEW

**Comment by DMXL** [comment]
Can anybody pls merge this PR?

**Comment by JounQin** [comment]
@alexmingoia @jbielick @wachunei

**Comment by wachunei** [comment]
I have no merging permissions :(

**Comment by JounQin** [comment]
@ZijianHe

**Comment by JounQin** [comment]
Fine, just close it in favor of https://github.com/koajs/koa-router .

**Pull request closed without merging**
